repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*.sql"
      - id: requirements-txt-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [
            "--max-line-length",
            "130",
            # Ignored flake8 rules are the following:
            # E203: "whitespace before ':'"
            # E266: "Too many leading # for a block comment"
            # W503: "line break occurred before binary operator"
            "--ignore",
            "E203,E266,W503",
          ]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
